'use client'

import { useState, useMemo } from 'react'
import { Copy, Check, Search, Filter, Facebook, Users, Car, Wrench, Zap, Mountain, Heart } from 'lucide-react'

type Character = 'don-match' | 'car-mela' | 'matchy' | 'car-litos'
type Category = 'negocios' | 'vehiculos'

interface AdPrompt {
    id: number
    title: string
    character: Character
    category: Category
    subcategory: string
    prompt: string
    hook: string
    cta: string
    segmentacion: {
        edad: string
        ubicacion: string
        intereses: string
    }
}

const characters: Record<Character, { name: string; age: number; gender: string; icon: any; color: string }> = {
    'don-match': { name: 'Don Match', age: 45, gender: 'Hombre', icon: Wrench, color: 'text-blue-400' },
    'car-mela': { name: 'Car-mela', age: 42, gender: 'Mujer', icon: Heart, color: 'text-pink-400' },
    'matchy': { name: 'Matchy', age: 20, gender: 'Mujer', icon: Zap, color: 'text-purple-400' },
    'car-litos': { name: 'Car-litos', age: 18, gender: 'Hombre', icon: Mountain, color: 'text-orange-400' }
}

const allPrompts: AdPrompt[] = [
    // === NEGOCIOS - DON MATCH ===
    { id: 1, title: 'Taller Mecanico', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing confidently in front of a busy mechanic workshop in Mexico City. He is pointing directly at the camera with a warm smile, holding a smartphone showing the CarMatch app. Behind him, a mechanic in blue overalls is working under a car hood with tools scattered around. The workshop has oil stains on concrete, fluorescent lights overhead, and spare parts on shelves. Bold white text overlay reads "TIENES TALLER MECANICO?" with a purple CarMatch logo in the corner. Photorealistic style, warm golden hour lighting, high contrast, professional Facebook ad photography, 1080x1080 square format.', hook: '¿Tienes taller mecanico? Publicalo gratis en CarMatch y que te encuentren los clientes', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Mecanica automotriz, talleres, negocios, emprendimiento, herramientas' } },
    { id: 2, title: 'Taller de Frenos', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a brake lathe machine in a brake workshop. He holds up a brake pad toward the camera with a confident expression. Behind him, a car is lifted on a hydraulic hoist with its wheels removed, showing brake discs. The workshop has stacks of brake pads and rotors on metal shelves. Bold white text overlay reads "¿ERES ESPECIALISTA EN FRENOS?" with a purple CarMatch logo. Photorealistic, warm lighting, professional Facebook ad style, 1080x1080.', hook: 'Especialista en frenos? Miles de personas buscan tu servicio HOY', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Frenos, mecanica, seguridad vial, talleres automotrices' } },
    { id: 3, title: 'Taller Electrico', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing inside an electrical auto repair shop. He is holding a multimeter probe in one hand and pointing at the camera with the other. Behind him, a car with its hood open shows visible wiring and electrical components. Diagnostic computers and oscilloscopes are on workbenches. Bold white text overlay reads "¿SABES ARREGLAR FALLAS ELECTRICAS?" with a purple CarMatch logo. Photorealistic, cool blue and warm orange lighting, professional Facebook ad style, 1080x1080.', hook: 'Sabes arreglar fallas electricas? Tu negocio necesita estar en el mapa', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Electricidad automotriz, diagnostico, talleres, electronica' } },
    { id: 4, title: 'Hojalateria y Pintura', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing in a body shop with a freshly painted car fender on a stand. He is gesturing toward the camera with an inviting smile. Behind him, a car masked with plastic sheets is being prepped for painting. The shop has paint guns hanging on the wall, color mixing station, and compressed air hoses. Bold white text overlay reads "¿TIENES TALLER DE HOJALATERIA Y PINTURA?" with a purple CarMatch logo. Photorealistic, dramatic workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes taller de hojalateria? Publicalo y recibe clientes reales', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Hojalateria, pintura automotriz, colision, talleres' } },
    { id: 5, title: 'Llantera', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing in a tire shop with rows of new tires stacked behind him. He holds a tire iron and points at the camera with a grin. A car is on a lift with one wheel removed. The shop has tire balancing machines and colorful tire displays. Bold white text overlay reads "¿TIENES LLANTERA?" with a purple CarMatch logo. Photorealistic, bright workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes llantera? Los que pinchazos te buscan AQUI', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Llantas, neumaticos, vulcanizadora, seguridad vial, talleres' } },
    { id: 8, title: 'Refaccionaria', character: 'don-match', category: 'negocios', subcategory: 'Refacciones', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing inside an auto parts store holding up an oil filter toward the camera. Behind him, shelves are packed with filters, belts, spark plugs, and car parts in colorful boxes. The store is well-lit with organized displays and price tags. Bold white text overlay reads "¿VENDES REFACCIONES?" with a purple CarMatch logo. Photorealistic, warm retail lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes refacciones? Publica tu inventario en CarMatch', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Refacciones, autopartes, mecanica, repuestos, negocios' } },
    { id: 12, title: 'Transmisiones', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a transmission on a workbench. He holds a torque wrench and looks at the camera. Behind him, disassembled transmission parts are laid out, clutch plates, gears, and a transmission jack. Bold white text overlay reads "¿SABES DE TRANSMISIONES?" with a purple CarMatch logo. Photorealistic, industrial workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Especialista en transmisiones? CarMatch te conecta con clientes', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Transmisiones, caja de cambios, clutch, mecanica especializada' } },
    { id: 16, title: 'Taller de Mofles', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing in an exhaust shop next to a car on a lift. He holds a stainless steel muffler toward the camera. Behind him, exhaust pipes, mufflers, and catalytic converters hang on the wall. Welding equipment and pipe bending tools are visible. Bold white text overlay reads "¿INSTALAS MOFLES?" with a purple CarMatch logo. Photorealistic, industrial workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Instalas mofles? Tu negocio necesita visibilidad', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Escape, mofles, sonido, rendimiento, talleres' } },
    { id: 17, title: 'Taller de Radiadores', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a car with its radiator exposed. He holds a radiator cap and points at the camera. Behind him, new radiators are displayed, coolant tanks, pressure testing equipment, and hoses. Bold white text overlay reads "¿ESPECIALISTA EN RADIADORES?" with a purple CarMatch logo. Photorealistic, clean workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Especialista en radiadores? Publicalo gratis en CarMatch', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Radiadores, enfriamiento, refrigeracion, mecanica, talleres' } },
    { id: 18, title: 'Rectificadora', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a cylinder head on a surface grinder machine. He holds a feeler gauge and looks at the camera. Behind him, engine blocks, cylinder heads, and precision measuring tools are organized on workbenches. Bold white text overlay reads "¿TIENES RECTIFICADORA?" with a purple CarMatch logo. Photorealistic, precision workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes rectificadora? Los mecanicos te buscan para referirte', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Rectificacion, cylinder head, engine rebuild, maquinaria, mecanica' } },
    { id: 20, title: 'Taller Diesel', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a diesel engine on a stand. He holds a fuel injector and looks at the camera. Behind him, diesel trucks, turbochargers, injection pumps, and diagnostic computers for diesel systems. Bold white text overlay reads "¿ESPECIALISTA EN DIESEL?" with a purple CarMatch logo. Photorealistic, heavy-duty workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Especialista en diesel? Miles de camionetas te necesitan', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Diesel, camionetas, turbo, inyeccion, mecanica pesada' } },
    { id: 21, title: 'Taller Offroad 4x4', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a lifted 4x4 truck in an offroad garage. He holds a suspension spring and points at the camera. Behind him, offroad vehicles with big tires, winches, snorkels, and roll cages. Mud and dirt on the floor. Bold white text overlay reads "¿TALLER OFFROAD 4X4?" with a purple CarMatch logo. Photorealistic, rugged garage lighting, professional Facebook ad style, 1080x1080.', hook: 'Taller 4x4? La comunidad offroad te esta buscando', cta: 'Publica Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Offroad, 4x4, terrenos, aventura, trucks, camionetas' } },
    { id: 26, title: 'Taller de Suspension', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a car on an alignment rack. He holds a suspension component (control arm) and looks at the camera. Behind him, alignment machines, shock absorbers, springs, and stabilizer bars are displayed. Bold white text overlay reads "¿ESPECIALISTA EN SUSPENSION?" with a purple CarMatch logo. Photorealistic, precision workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Especialista en suspension? Los clientes te buscan', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Suspension, amortiguadores, alineacion, balanceo, mecanica' } },
    { id: 31, title: 'Laboratorio de Inyectores', character: 'don-match', category: 'negocios', subcategory: 'Especializado', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing in a fuel injector testing lab. He holds a clean fuel injector toward the camera. Behind him, injector testing machines, ultrasonic cleaning baths, and fuel rail components are visible. Bold white text overlay reads "¿LIMPIAS INYECTORES?" with a purple CarMatch logo. Photorealistic, laboratory-quality lighting, professional Facebook ad style, 1080x1080.', hook: 'Limpies inyectores? Los mecanicos te buscan para referir', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Inyectores, limpieza, rendimiento, motor, mecanica especializada' } },
    { id: 34, title: 'Taller EV e Hibrido', character: 'don-match', category: 'negocios', subcategory: 'Especializado', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a Tesla being serviced in a specialized EV garage. He holds a high-voltage diagnostic tool and looks at the camera. Behind him, electric car battery packs, high-voltage cables, and specialized EV tools. Bold white text overlay reads "¿TALLER EV E HIBRIDO?" with a purple CarMatch logo. Photorealistic, modern clean workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Especialista en electricos? El futuro esta aqui, publicate', cta: 'Publica Gratis', segmentacion: { edad: '25-50', ubicacion: 'Mexico', intereses: 'Electrico, hibrido, Tesla, baterias, futuro, tecnologia' } },
    { id: 35, title: 'Cambio de Aceite', character: 'don-match', category: 'negocios', subcategory: 'Mecanica', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing at an oil change bay with a car on a lift. He holds a bottle of motor oil and smiles. Behind him, oil drums, oil filter display, drain pans, and quick-lube equipment. Bold white text overlay reads "¿SERVICIO DE LUBRICANTES?" with a purple CarMatch logo. Photorealistic, bright workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Servicio de lubricantes? Publicalo y recibe clientes hoy', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Aceite, lubricantes, cambio de aceite, mantenimiento, motor' } },

    // === NEGOCIOS - CAR-MELA ===
    { id: 6, title: 'Autolavado / Estetica', character: 'car-mela', category: 'negocios', subcategory: 'Estetica', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing at a car wash with a pressure washer in hand, spraying water on a shiny SUV. She looks at the camera with a thumbs up. Behind her, other workers are washing cars, soap suds everywhere, colorful towels hanging. The car wash has bright neon lights and wet concrete. Bold white text overlay reads "¿TU AUTOLAVADO SE VE VACIO?" with a purple CarMatch logo. Photorealistic, vibrant colors, professional Facebook ad style, 1080x1080.', hook: 'Tu autolavado se ve vacio? Llenalo de clientes con CarMatch', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Autolavado, estetica, limpieza, cuidado del auto, negocios' } },
    { id: 7, title: 'Detallado Profesional', character: 'car-mela', category: 'negocios', subcategory: 'Estetica', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a car with a mirror-like finish in a detailing studio. She holds a microfiber cloth and gestures toward the glossy paint. The studio has LED inspection lights, polishers, ceramic coating bottles, and organized tool carts. Bold white text overlay reads "¿HACES DETALLADO PROFESIONAL?" with a purple CarMatch logo. Photorealistic, studio lighting, professional Facebook ad style, 1080x1080.', hook: 'Haces detallado o ceramico? Publica tu negocio GRATIS', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Detallado, ceramico, pulido, proteccion de pintura, detailing' } },
    { id: 10, title: 'Cristales Automotriz', character: 'car-mela', category: 'negocios', subcategory: 'Especializado', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a car with a cracked windshield being repaired. She holds a glass repair tool and smiles at the camera. The shop has racks of replacement windshields, glass cutting tools, and urethane sealant tubes. Bold white text overlay reads "¿REPARAS PARABRISAS?" with a purple CarMatch logo. Photorealistic, natural daylight from shop entrance, professional Facebook ad style, 1080x1080.', hook: 'Reparas parabrisas? Tus clientes te encuentran aqui', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Cristales, parabrisas, reparacion, seguro auto, talleres' } },
    { id: 11, title: 'Tapiceria Automotriz', character: 'car-mela', category: 'negocios', subcategory: 'Especializado', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing in an upholstery shop holding a leather sample. Behind her, a car seat is being reupholstered, fabric rolls in various colors and textures are on racks. Sewing machines and leather working tools are visible. Bold white text overlay reads "¿TIENES TALLER DE TAPICERIA?" with a purple CarMatch logo. Photorealistic, warm workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes taller de tapiceria? Publicalo gratis HOY', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Tapiceria, cuero, interior, restauracion, talleres' } },
    { id: 22, title: 'Cerrajeria Automotriz', character: 'car-mela', category: 'negocios', subcategory: 'Especializado', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing in a locksmith shop holding a car key fob being programmed. Behind her, key cutting machines, transponder programming devices, and rows of key blanks. Bold white text overlay reads "¿TIENES CERRAJERIA AUTOMOTRIZ?" with a purple CarMatch logo. Photorealistic, professional shop lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes cerrajeria? Cuando pierden sus llaves, te buscan AQUI', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Cerrajeria, llaves, transponder, seguridad, emergencias' } },
    { id: 23, title: 'Gasolinera', character: 'car-mela', category: 'negocios', subcategory: 'Servicios', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing at a gas station holding a fuel nozzle. She smiles at the camera with a thumbs up. Behind her, gas pumps, the station canopy, and cars refueling. Bold white text overlay reads "¿TIENES GASOLINERA?" with a purple CarMatch logo. Photorealistic, bright outdoor lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes gasolinera? Aparece en el mapa para que te encuentren', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Gasolinera, combustible, servicio, estacion, negocios' } },
    { id: 24, title: 'Yonke / Partes Usadas', character: 'car-mela', category: 'negocios', subcategory: 'Refacciones', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing in a junkyard surrounded by wrecked and salvaged cars. She holds a car part (alternator) and gestures at the camera. Rows of cars in various states of disassembly stretch behind her. Bold white text overlay reads "¿VENDES PARTES USADAS?" with a purple CarMatch logo. Photorealistic, outdoor salvage yard lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes partes usadas? Publica tu inventario gratis', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Yonke, partes usadas, refacciones, salvage, negocios' } },
    { id: 25, title: 'Estacionamiento', character: 'car-mela', category: 'negocios', subcategory: 'Servicios', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing at the entrance of a parking garage. She holds a parking ticket and gestures welcomingly. Behind her, parked cars are visible in the well-lit garage with parking signs and barriers. Bold white text overlay reads "¿TIENES ESTACIONAMIENTO?" with a purple CarMatch logo. Photorealistic, clean modern parking facility, professional Facebook ad style, 1080x1080.', hook: 'Tienes estacionamiento? Publicalo para que te encuentren', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Estacionamiento, parking, estacionar, centro, negocios' } },
    { id: 27, title: 'Aire Acondicionado', character: 'car-mela', category: 'negocios', subcategory: 'Especializado', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a car with its AC system being serviced. She holds a manifold gauge set and points at the camera. Behind her, AC recovery machines, refrigerant cans, and evaporator cores. Bold white text overlay reads "¿SERVICIO DE AIRE ACONDICIONADO?" with a purple CarMatch logo. Photorealistic, clean workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Servicio de aire acondicionado? Publicalo HOY gratis', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Aire acondicionado, AC, clima, refrigeracion, confort' } },
    { id: 29, title: 'Polarizado / Vinil', character: 'car-mela', category: 'negocios', subcategory: 'Estetica', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a car being wrapped with colored vinyl. She holds a squeegee tool and smiles at the camera. Behind her, rolls of vinyl in various colors and finishes (matte, chrome, carbon fiber) are on a rack. Bold white text overlay reads "¿HACES POLARIZADO O VINIL?" with a purple CarMatch logo. Photorealistic, bright workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Haces polarizado o wrap? Tus clientes te encuentran aqui', cta: 'Publica Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Polarizado, vinil, wrap, proteccion, customizacion, color' } },
    { id: 32, title: 'Rotulacion / Wrap', character: 'car-mela', category: 'negocios', subcategory: 'Estetica', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing in a sign shop next to a car being vinyl-wrapped with a business logo. She holds a weeding tool and points at the camera. Behind her, vinyl cutters, printed wraps, squeegees, and heat guns. Bold white text overlay reads "¿HACES ROTULACION O WRAP?" with a purple CarMatch logo. Photorealistic, commercial signage shop lighting, professional Facebook ad style, 1080x1080.', hook: 'Haces rotulacion comercial? Publica tus trabajos', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Rotulacion, wrap, vinil, publicidad, identification comercial' } },
    { id: 36, title: 'Auto Boutique', character: 'car-mela', category: 'negocios', subcategory: 'Servicios', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing in an auto accessories boutique. She holds a stylish car floor mat and shows it to the camera. Behind her, displays of seat covers, steering wheel covers, phone holders, car perfumes, and premium accessories. Bold white text overlay reads "¿VENDES ACCESORIOS AUTOMOTRICES?" with a purple CarMatch logo. Photorealistic, boutique retail lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes accesorios automotrices? Publica tu tienda gratis', cta: 'Publica Gratis', segmentacion: { edad: '25-50', ubicacion: 'Mexico', intereses: 'Accesorios, accesorios auto, tapetes, perfumes, gadgets' } },
    { id: 37, title: 'Hospital / Urgencias', character: 'car-mela', category: 'negocios', subcategory: 'Servicios', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing at a hospital emergency entrance with an ambulance in the background. She holds a phone showing the CarMatch app map. Behind her, the hospital entrance with red cross symbol, medical staff, and emergency vehicles. Bold white text overlay reads "¿TIENES HOSPITAL O URGENCIAS?" with a purple CarMatch logo. Photorealistic, professional medical facility lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes hospital? Aparece en el mapa para emergencias', cta: 'Publica Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Hospital, emergencias, salud, ambulancia, seguridad' } },
    { id: 38, title: 'Policia / Transito', character: 'car-mela', category: 'negocios', subcategory: 'Servicios', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing at a police station entrance with a patrol car behind her. She holds a phone showing the CarMatch app map. Behind her, police officers, the station facade with official insignia, and emergency lights. Bold white text overlay reads "¿ESTACION DE POLICIA?" with a purple CarMatch logo. Photorealistic, official facility lighting, professional Facebook ad style, 1080x1080.', hook: 'Estacion de policia? Aparece en CarMatch para emergencias', cta: 'Publica Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Policia, seguridad, emergencias, transito, denuncias' } },
    { id: 39, title: 'Aeropuerto', character: 'car-mela', category: 'negocios', subcategory: 'Servicios', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing at an airport terminal entrance with planes visible through the windows behind her. She holds a phone showing the CarMatch app map and gestures welcomingly. Behind her, the airport terminal, travelers with luggage, and aircraft on the tarmac. Bold white text overlay reads "¿TIENES AEROPUERTO?" with a purple CarMatch logo. Photorealistic, bright airport terminal lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes aeropuerto? Publica en CarMatch para viajeros', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Aeropuerto, viajes, vuelos, turismo, transporte aereo' } },

    // === NEGOCIOS - MATCHY ===
    { id: 9, title: 'Audio y Alarmas', character: 'matchy', category: 'negocios', subcategory: 'Tecnologia', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing in a car audio shop holding a subwoofer speaker. Behind her, display walls show speakers, amplifiers, head units, and alarm systems with neon accent lighting. A car is being fitted with a custom sound system. Bold white text overlay reads "¿INSTALAS ESTEREOS Y ALARMAS?" with a purple CarMatch logo. Photorealistic, neon-lit atmosphere, professional Facebook ad style, 1080x1080.', hook: 'Instalas estereos y alarmas? Te estamos buscando', cta: 'Publica Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Audio automotriz, estereos, alarmas, seguridad, customizacion' } },
    { id: 13, title: 'Servicio de Gruas', character: 'matchy', category: 'negocios', subcategory: 'Servicios', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a tow truck on a highway at sunset. She holds a two-way radio and gestures at the camera. The tow truck has flashing amber lights, and a car is being loaded onto the flatbed. Bold white text overlay reads "¿TIENES GRUA?" with a purple CarMatch logo. Photorealistic, dramatic sunset lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes grua? Publicate y que te llamen cuando te necesiten', cta: 'Publica Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Grua, asistencia vial, emergencias, transporte, carreteras' } },
    { id: 15, title: 'Modificaciones / Tuning', character: 'matchy', category: 'negocios', subcategory: 'Tecnologia', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a car with a custom wide body kit and neon underglow in a tuning garage. She holds a paint gun and looks at the camera. Behind her, cars with spoilers, custom wheels, and body modifications are being worked on. Bold white text overlay reads "¿HACES TUNING Y MODIFICACIONES?" with a purple CarMatch logo. Photorealistic, neon-lit garage atmosphere, professional Facebook ad style, 1080x1080.', hook: 'Haces tuning? Publica tus trabajos y atrae mas clientes', cta: 'Publica Gratis', segmentacion: { edad: '18-40', ubicacion: 'Mexico', intereses: 'Tuning, modificacion, custom cars, neones, spoilers, rines' } },
    { id: 19, title: 'Taller de Blindaje', character: 'matchy', category: 'negocios', subcategory: 'Especializado', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing inside an armored vehicle conversion shop. She gestures toward a car being fitted with ballistic panels. Behind her, bulletproof glass samples, armored doors, and armoring materials are displayed. Bold white text overlay reads "¿HACES BLINDAJE AUTOMOTRIZ?" with a purple CarMatch logo. Photorealistic, secure facility lighting, professional Facebook ad style, 1080x1080.', hook: 'Haces blindaje automotriz? Tu servicio es unico, publicalo', cta: 'Publica Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Blindaje, seguridad, proteccion, vehiculos blindados, defensa' } },
    { id: 28, title: 'Importadoras', character: 'matchy', category: 'negocios', subcategory: 'Servicios', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing in a showroom with imported luxury cars. She gestures proudly at the vehicles. Behind her, sleek European and Japanese cars on display, import documentation on a desk, international shipping containers visible through a window. Bold white text overlay reads "¿IMPORTAS VEHICULOS?" with a purple CarMatch logo. Photorealistic, showroom lighting, professional Facebook ad style, 1080x1080.', hook: 'Importas vehiculos? Publica tu inventario en CarMatch', cta: 'Publica Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Importacion, autos importados, aduana, vehiculos exclusivos' } },
    { id: 30, title: 'Iluminacion LED', character: 'matchy', category: 'negocios', subcategory: 'Tecnologia', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing in an LED lighting shop holding an LED headlight bulb. Behind her, displays of LED bars, headlights, tail lights, and interior lighting with bright LED strips. Bold white text overlay reads "¿INSTALAS FAROS LED?" with a purple CarMatch logo. Photorealistic, bright LED-lit atmosphere, professional Facebook ad style, 1080x1080.', hook: 'Instalas faros LED? Publica tu negocio gratis', cta: 'Publica Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Iluminacion, LED, faros, customizacion, seguridad' } },
    { id: 33, title: 'Electrolinera', character: 'matchy', category: 'negocios', subcategory: 'Tecnologia', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing at an EV charging station plugging a charger into an electric car. She smiles at the camera. Behind her, multiple charging stations with green energy symbols, solar panels on the roof, and electric vehicles charging. Bold white text overlay reads "¿TIENES CARGADOR ELECTRICO?" with a purple CarMatch logo. Photorealistic, modern green energy lighting, professional Facebook ad style, 1080x1080.', hook: 'Tienes cargador electrico? Aparece en el mapa de CarMatch', cta: 'Publica Gratis', segmentacion: { edad: '25-50', ubicacion: 'Mexico', intereses: 'Electrico, EV, carga, sostenible, electromovilidad, futuro' } },

    // === NEGOCIOS - CAR-LITOS ===
    { id: 14, title: 'Taller de Motos', character: 'car-litos', category: 'negocios', subcategory: 'Motos', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing in a motorcycle repair shop. He holds a motorcycle spark plug and smiles. Behind him, motorcycles of various types are on lifts, oil change equipment, tire changing tools, and motorcycle parts on shelves. Bold white text overlay reads "¿TALLER DE MOTOS?" with a purple CarMatch logo. Photorealistic, bright workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Taller de motos? La comunidad de motociclistas te busca', cta: 'Publica Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Motocicletas, motos, mecanica, talleres, motociclismo' } },

    // === VEHICULOS - CAR-MELA (Familia, Lujo, Transporte) ===
    { id: 101, title: 'Sedan', character: 'car-mela', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a silver sedan in a clean showroom. She gestures toward the car and looks at the camera. The sedan is polished, wheels clean, interior visible through windows. Bold white text overlay reads "VENDES TU SEDAN?" with a purple CarMatch logo. Photorealistic, showroom lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu sedan? Publicalo gratis y llega a miles de compradores', cta: 'Vende Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Autos, sedan, compra-venta, vehiculos usados' } },
    { id: 102, title: 'SUV', character: 'car-mela', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a white SUV parked on a scenic road. She gives a thumbs up toward the camera. The SUV is clean, family-sized, with roof rails visible. Bold white text overlay reads "VENDES TU SUV?" with a purple CarMatch logo. Photorealistic, natural outdoor lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una SUV? Las familias la estan buscando en CarMatch', cta: 'Vende Gratis', segmentacion: { edad: '28-55', ubicacion: 'Mexico', intereses: 'SUV, familia, compra-venta, vehiculos usados, seguridad' } },
    { id: 108, title: 'Minivan', character: 'car-mela', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a minivan with its sliding door open, showing spacious interior. She gestures welcomingly toward the camera. The minivan is family-oriented, with three rows of seats visible. Bold white text overlay reads "VENDES TU MINIVAN?" with a purple CarMatch logo. Photorealistic, suburban driveway lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu minivan? Las familias grandes la necesitan', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Minivan, familia, viajes, espacio, practical' } },
    { id: 109, title: 'Wagon', character: 'car-mela', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a station wagon in a mountainous landscape. She leans against the car and looks at the camera. The wagon has roof rails, cargo space, and outdoor gear visible. Bold white text overlay reads "VENDES TU WAGON?" with a purple CarMatch logo. Photorealistic, mountain scenery lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu wagon? Publicalo y que te encuentren', cta: 'Vende Gratis', segmentacion: { edad: '28-50', ubicacion: 'Mexico', intereses: 'Wagon, familiar, aventura, carga, outdoors' } },
    { id: 110, title: 'Crossover', character: 'car-mela', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a crossover SUV in a suburban neighborhood. She gives a thumbs up toward the camera. The crossover is sleek, modern, with a raised ride height and contemporary styling. Bold white text overlay reads "VENDES TU CROSSOVER?" with a purple CarMatch logo. Photorealistic, suburban golden hour lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu crossover? Es el mas buscado del mercado', cta: 'Vende Gratis', segmentacion: { edad: '25-50', ubicacion: 'Mexico', intereses: 'Crossover, SUV, moderno, compra-venta, popular' } },
    { id: 111, title: 'Limusina', character: 'car-mela', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Car-mela, a 42-year-old Mexican woman with a kind organized demeanor, wearing a dark blue CarMatch jacket, standing next to a stretch limousine in front of a luxury hotel. She opens the rear door and looks at the camera. The limousine is black, long, with tinted windows and chrome accents. Bold white text overlay reads "VENDES UNA LIMUSINA?" with a purple CarMatch logo. Photorealistic, luxury hotel entrance lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una limusina? Publicalo gratis en CarMatch', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Limusina, lujo, eventos, bodas, transporte premium' } },

    // === VEHICULOS - DON MATCH (Camiones, Pickups) ===
    { id: 103, title: 'Pickup', character: 'don-match', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a black pickup truck at a construction site. He holds a hard hat and points at the camera. The pickup is rugged, with a bed loaded with tools. Bold white text overlay reads "VENDES TU PICKUP?" with a purple CarMatch logo. Photorealistic, outdoor construction site lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu pickup? Los que trabajan la necesitan', cta: 'Vende Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Pickup, trabajo, construccion, camioneta, compra-venta' } },

    // === VEHICULOS - MATCHY (Deportivos, Exclusivos) ===
    { id: 104, title: 'Deportivo', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a red sports car on a racetrack. She leans against the car and looks at the camera. The sports car is low, aerodynamic, with aggressive styling and large alloy wheels. Bold white text overlay reads "VENDES TU DEPORTIVO?" with a purple CarMatch logo. Photorealistic, dramatic racetrack lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu deportivo? Los entusiastas te encuentran aqui', cta: 'Vende Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Deportivos, speed, performance, autos exclusivos, racing' } },
    { id: 105, title: 'Convertible', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a convertible with its top down on a coastal road. She smiles at the camera with the ocean in the background. The convertible is sleek, with leather interior visible. Bold white text overlay reads "VENDES TU CONVERTIBLE?" with a purple CarMatch logo. Photorealistic, golden hour coastal lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu convertible? Publicalo gratis en CarMatch', cta: 'Vende Gratis', segmentacion: { edad: '25-50', ubicacion: 'Mexico', intereses: 'Convertible, descapotable, estilo, playas, verano' } },
    { id: 106, title: 'Coupe', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a sporty coupe in an urban parking garage. She looks at the camera with a confident pose. The coupe is two-door, aggressive design, with LED headlights on. Bold white text overlay reads "VENDES TU COUPE?" with a purple CarMatch logo. Photorealistic, urban garage lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu coupe? Los compradores te buscan', cta: 'Vende Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Coupe, deportivos, estilo, compra-venta, autos' } },
    { id: 107, title: 'Hatchback', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a compact hatchback in a city street. She points at the car and looks at the camera. The hatchback is colorful, practical, with a modern design. Bold white text overlay reads "VENDES TU HATCHBACK?" with a purple CarMatch logo. Photorealistic, urban street lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu hatchback? Es el auto perfecto para la ciudad', cta: 'Vende Gratis', segmentacion: { edad: '22-45', ubicacion: 'Mexico', intereses: 'Hatchback, compactos, ciudad, economico, primer auto' } },
    { id: 112, title: 'Microcar', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a tiny microcar on a narrow city street. She crouches next to it and smiles at the camera. The microcar is compact, electric, with a futuristic design. Bold white text overlay reads "VENDES TU MICROCAR?" with a purple CarMatch logo. Photorealistic, urban street lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu microcar? Economico y perfecto para la ciudad', cta: 'Vende Gratis', segmentacion: { edad: '22-45', ubicacion: 'Mexico', intereses: 'Microcar, electrico, economico, ciudad, compacto' } },
    { id: 113, title: 'Roadster', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a classic roadster with its top down on a scenic mountain road. She leans against the car and looks at the camera. The roadster is vintage-inspired, with a long hood and short deck. Bold white text overlay reads "VENDES TU ROADSTER?" with a purple CarMatch logo. Photorealistic, mountain road golden hour lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu roadster? Los amantes de la velocidad te buscan', cta: 'Vende Gratis', segmentacion: { edad: '28-50', ubicacion: 'Mexico', intereses: 'Roadster, clasico, velocidad, coleccion, exclusivo' } },
    { id: 114, title: 'Moke', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a Moke-style open vehicle on a beach. She sits on the hood and looks at the camera. The Moke is colorful, open-top, with a fun tropical vibe. Bold white text overlay reads "VENDES TU MOKE?" with a purple CarMatch logo. Photorealistic, beach sunset lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu moke? Es un clasico, publicalo', cta: 'Vende Gratis', segmentacion: { edad: '25-50', ubicacion: 'Mexico', intereses: 'Moke, clasico, playa, tropical, vintage, diversion' } },
    { id: 115, title: 'Targa', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a targa-top sports car. She holds the removable roof panel and smiles at the camera. The car has a distinctive targa bar and open-top design. Bold white text overlay reads "VENDES TU TARGA?" with a purple CarMatch logo. Photorealistic, scenic coastal road lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu targa? Publicalo gratis en CarMatch', cta: 'Vende Gratis', segmentacion: { edad: '28-50', ubicacion: 'Mexico', intereses: 'Targa, deportivo, exclusivo, coleccion, estilo' } },
    { id: 116, title: 'Shooting Brake', character: 'matchy', category: 'vehiculos', subcategory: 'Automovil', prompt: 'Matchy, a 20-year-old Mexican woman with trendy style and creative energy, wearing a dark blue CarMatch jacket, standing next to a shooting brake grand tourer in a luxury garage. She gestures toward the car and looks at the camera. The car has an elongated roofline, sporty elegance, with premium finishes. Bold white text overlay reads "VENDES TU SHOOTING BRAKE?" with a purple CarMatch logo. Photorealistic, luxury garage lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu shooting brake? Unico, publicalo ya', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Shooting brake, exclusivo, gran turismo, lujo, unico' } },

    // === VEHICULOS - CAR-LITOS (Motos, Off-road, Maquinaria) ===
    { id: 201, title: 'Moto Deportiva', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a red sport motorcycle on a racetrack. He holds a helmet and looks at the camera. The motorcycle is aggressive, with full fairings, clip-on handlebars, and a racing stance. Bold white text overlay reads "VENDES TU MOTO DEPORTIVA?" with a purple CarMatch logo. Photorealistic, racetrack lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu moto deportiva? La comunidad te busca', cta: 'Vende Gratis', segmentacion: { edad: '22-40', ubicacion: 'Mexico', intereses: 'Motocicleta deportiva, 600cc, 1000cc, racing, velocidad' } },
    { id: 202, title: 'Moto Cruiser', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a chrome cruiser motorcycle on a desert highway. He leans against the bike and looks at the camera. The cruiser has high handlebars, leather saddlebags, and a relaxed riding position. Bold white text overlay reads "VENDES TU CRUISER?" with a purple CarMatch logo. Photorealistic, desert highway golden hour lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu cruiser? Los motociclistas te compran', cta: 'Vende Gratis', segmentacion: { edad: '28-50', ubicacion: 'Mexico', intereses: 'Cruiser, Harley, motociclismo, carretera, libertad' } },
    { id: 203, title: 'Moto Touring', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a touring motorcycle loaded with panniers and a top case. He gestures toward the camera. The touring bike has a large windscreen, comfortable seats, and luggage system. Bold white text overlay reads "VENDES TU TOURING?" with a purple CarMatch logo. Photorealistic, mountain road scenery lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu touring? Para viajes largos, publicalo', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Touring, viajes, motociclismo, aventura, largo alcance' } },
    { id: 204, title: 'Moto Off-road', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a dual-sport motorcycle on a dirt trail. He holds riding gear and looks at the camera. The bike has knobby tires, high fenders, and long-travel suspension. Bold white text overlay reads "VENDES TU MOTO OFF-ROAD?" with a purple CarMatch logo. Photorealistic, off-road trail lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu moto off-road? Los aventureros la buscan', cta: 'Vende Gratis', segmentacion: { edad: '22-45', ubicacion: 'Mexico', intereses: 'Off-road, enduro, aventura, terraceria, trail' } },
    { id: 205, title: 'Scooter', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a scooter on a city street. He sits on the scooter and looks at the camera. The scooter is modern, practical, with under-seat storage visible. Bold white text overlay reads "VENDES TU SCOOTER?" with a purple CarMatch logo. Photorealistic, urban street lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu scooter? Perfecto para la ciudad', cta: 'Vende Gratis', segmentacion: { edad: '22-45', ubicacion: 'Mexico', intereses: 'Scooter, ciudad, practico, economico, deliveries' } },
    { id: 206, title: 'Chopper', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a custom chopper motorcycle. He holds a wrench and looks at the camera. The chopper has extended forks, custom paint, sissy bar, and chrome details. Bold white text overlay reads "VENDES TU CHOPPER?" with a purple CarMatch logo. Photorealistic, garage workshop lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu chopper? Publicalo gratis en CarMatch', cta: 'Vende Gratis', segmentacion: { edad: '28-50', ubicacion: 'Mexico', intereses: 'Chopper, custom, motociclismo, personalizacion, estilo' } },
    { id: 207, title: 'Naked', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a naked streetfighter motorcycle in an urban setting. He looks at the camera with the bike. The naked has minimal bodywork, exposed engine, upright handlebars. Bold white text overlay reads "VENDES TU NAKED?" with a purple CarMatch logo. Photorealistic, urban evening lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu naked? Los motociclistas te encuentran', cta: 'Vende Gratis', segmentacion: { edad: '22-40', ubicacion: 'Mexico', intereses: 'Naked, streetfighter, ciudad, practico, potencia' } },
    { id: 208, title: 'Dual-Sport', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a dual-sport motorcycle at a trail intersection. He points at the camera. The bike has both street and off-road capabilities, handguards, crash bars. Bold white text overlay reads "VENDES TU DUAL-SPORT?" with a purple CarMatch logo. Photorealistic, trail intersection lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu dual-sport? Carretera y terraceria', cta: 'Vende Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Dual-sport, aventura, versatility, trail, carretera' } },
    { id: 209, title: 'Adventure', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a large adventure motorcycle loaded with aluminum panniers. He gestures toward a mountainous landscape behind him. The bike has crash bars, skid plate, tall windscreen. Bold white text overlay reads "VENDES TU ADVENTURE?" with a purple CarMatch logo. Photorealistic, mountain scenery lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu adventure? Los viajeros la buscan', cta: 'Vende Gratis', segmentacion: { edad: '28-50', ubicacion: 'Mexico', intereses: 'Adventure, viajes, mototurismo, off-road, exploracion' } },
    { id: 210, title: 'Cafe Racer', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a cafe racer motorcycle. He holds a vintage helmet and looks at the camera. The cafe racer has clip-on handlebars, rear-set footpegs, retro paint scheme, and a solo seat cowl. Bold white text overlay reads "VENDES TU CAFE RACER?" with a purple CarMatch logo. Photorealistic, retro urban setting lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu cafe racer? Un clasico moderno', cta: 'Vende Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Cafe racer, retro, vintage, estilo, custom' } },
    { id: 211, title: 'Scrambler', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a scrambler motorcycle on a dirt path. He gives a thumbs up toward the camera. The scrambler has dual-purpose tires, high exhaust, minimal bodywork. Bold white text overlay reads "VENDES TU SCRAMBLER?" with a purple CarMatch logo. Photorealistic, countryside dirt road lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu scrambler? Publicalo gratis', cta: 'Vende Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Scrambler, retro, aventura, off-road ligero, estilo' } },
    { id: 212, title: 'Enduro', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to an enduro motorcycle. He holds goggles and looks at the camera. The enduro has long-travel suspension, knobby tires, high ground clearance, and race-ready components. Bold white text overlay reads "VENDES TU ENDURO?" with a purple CarMatch logo. Photorealistic, off-road terrain lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu enduro? Los de enduro te compran', cta: 'Vende Gratis', segmentacion: { edad: '22-40', ubicacion: 'Mexico', intereses: 'Enduro, competicion, off-road, terraceria, rally' } },
    { id: 213, title: 'Motocross', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a motocross bike at a dirt track. He holds a helmet with goggles. The motocross has knobby tires, high fenders, race numbers, and suspension tuned for jumps. Bold white text overlay reads "VENDES TU MOTOCROSS?" with a purple CarMatch logo. Photorealistic, motocross track lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu motocross? Publicalo y vende rapido', cta: 'Vende Gratis', segmentacion: { edad: '18-35', ubicacion: 'Mexico', intereses: 'Motocross, competicion, dirt track, salto, racing' } },
    { id: 214, title: 'Trial', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a trials motorcycle on rocky terrain. He balances on a rock and looks at the camera. The trials bike is lightweight, no seat, with grippy tires and minimal bodywork. Bold white text overlay reads "VENDES TU TRIAL?" with a purple CarMatch logo. Photorealistic, rocky terrain lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu trial? Los de trial te compran', cta: 'Vende Gratis', segmentacion: { edad: '25-45', ubicacion: 'Mexico', intereses: 'Trial, habilidad, rocas, technical riding, competicion' } },
    { id: 215, title: 'Triciclo / Spyder', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a Can-Am Spyder three-wheeled motorcycle. He opens the trunk and looks at the camera. The Spyder has two wheels in front, one in back, with a touring setup. Bold white text overlay reads "VENDES TU TRICICLO (SPYDER)?" with a purple CarMatch logo. Photorealistic, scenic road lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu triciclo (Spyder/Ryker)? Publicalo ya', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Spyder, Ryker, triciclo, Can-Am, touring, confort' } },
    { id: 216, title: 'Cuatrimoto / ATV', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a Yamaha RZR ATV in a desert landscape. He holds a helmet and looks at the camera. The ATV is aggressive, with roll cage, large tires, and sporty design. Bold white text overlay reads "VENDES TU CUATRIMOTO (ATV)?" with a purple CarMatch logo. Photorealistic, desert terrain lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu cuatrimoto? Los aventureros la buscan', cta: 'Vende Gratis', segmentacion: { edad: '22-45', ubicacion: 'Mexico', intereses: 'ATV, cuatrimoto, off-road, aventura, Polaris, Can-Am' } },
    { id: 217, title: 'Moped', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, sitting on a moped on a city sidewalk. He smiles at the camera. The moped is small, practical, with pedals and a small engine. Bold white text overlay reads "VENDES TU MOPED?" with a purple CarMatch logo. Photorealistic, urban street lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu moped? Economico y practico', cta: 'Vende Gratis', segmentacion: { edad: '18-40', ubicacion: 'Mexico', intereses: 'Moped, economico, ciudad, deliveries, practico' } },
    { id: 218, title: 'Pocket Bike', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, crouching next to a pocket bike on a garage floor. He holds the tiny motorcycle and looks at the camera. The pocket bike is miniature, with small wheels and a compact engine. Bold white text overlay reads "VENDES TU POCKET BIKE?" with a purple CarMatch logo. Photorealistic, garage lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu pocket bike? Publicalo gratis', cta: 'Vende Gratis', segmentacion: { edad: '18-35', ubicacion: 'Mexico', intereses: 'Pocket bike, mini moto, diversion, coleccion, karting' } },
    { id: 219, title: 'Supermoto', character: 'car-litos', category: 'vehiculos', subcategory: 'Motocicleta', prompt: 'Car-litos, an 18-year-old Mexican guy with energetic adventurous spirit, wearing a dark blue CarMatch jacket, standing next to a supermoto motorcycle on a paved track. He holds a helmet and looks at the camera. The supermoto has street tires on an enduro chassis, with aggressive styling. Bold white text overlay reads "VENDES TU SUPERMOTO?" with a purple CarMatch logo. Photorealistic, trackside lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes tu supermoto? Los motociclistas te buscan', cta: 'Vende Gratis', segmentacion: { edad: '22-40', ubicacion: 'Mexico', intereses: 'Supermoto, pista, enduro calle, competicion, agil' } },
    { id: 301, title: 'Tractocamion', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a large semi-truck (tractocamion) on a highway. He holds a CB radio mic and looks at the camera. The truck is chrome-heavy, with a sleeper cab, dual exhaust stacks, and polished fuel tanks. Bold white text overlay reads "VENDES UN TRACTOCAMION?" with a purple CarMatch logo. Photorealistic, highway sunset lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un tractocamion? Los transportistas te buscan', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Tractocamion, transporte, logistica, camionero, carretera' } },
    { id: 302, title: 'Torton', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a medium-duty box truck (torton) in a commercial area. He gestures toward the truck and looks at the camera. The torton has a closed cargo box, with company branding space. Bold white text overlay reads "VENDES UN TORTON?" with a purple CarMatch logo. Photorealistic, commercial area lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un torton? Publicalo gratis en CarMatch', cta: 'Vende Gratis', segmentacion: { edad: '28-55', ubicacion: 'Mexico', intereses: 'Torton, transporte de carga, negocio, distribucion' } },
    { id: 303, title: 'Rabon', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a small cargo truck (rabon) at a market. He holds a clipboard and looks at the camera. The rabon is compact, with an open cargo bed, ideal for local deliveries. Bold white text overlay reads "VENDES UN RABON?" with a purple CarMatch logo. Photorealistic, market area lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un rabon? Los comerciantes lo necesitan', cta: 'Vende Gratis', segmentacion: { edad: '25-55', ubicacion: 'Mexico', intereses: 'Rabon, distribucion, mercado, negocios, deliveries' } },
    { id: 304, title: 'Pickup Heavy Duty', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a heavy-duty pickup truck (Ford F-450/Chevy 4500) with a gooseneck trailer. He gives a thumbs up toward the camera. The pickup is massive, with dual rear wheels, towing mirrors, and a work-ready appearance. Bold white text overlay reads "VENDES UNA PICKUP HEAVY DUTY?" with a purple CarMatch logo. Photorealistic, ranch setting lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una pickup pesada? Para trabajo duro, publicalo', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Heavy duty, F-450, towing, trabajo, rancho, industria' } },
    { id: 305, title: 'Volteo', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a dump truck (volteo) at a construction site. He holds a hard hat and looks at the camera. The dump truck has a hydraulic bed, with gravel visible. Bold white text overlay reads "VENDES UN VOLTEO?" with a purple CarMatch logo. Photorealistic, construction site lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un volteo? Los de construccion te buscan', cta: 'Vende Gratis', segmentacion: { edad: '28-55', ubicacion: 'Mexico', intereses: 'Volteo, construccion, materiales, obra, transporte' } },
    { id: 306, title: 'Cisterna / Pipa', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a water tanker truck (cisterna/pipa) on a rural road. He gestures toward the truck and looks at the camera. The tanker has a large cylindrical tank, with water spraying from the back. Bold white text overlay reads "VENDES UNA CISTERNA (PIPA)?" with a purple CarMatch logo. Photorealistic, rural road lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una cisterna? Publicalo y vende', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Cisterna, pipa, agua, transporte de liquidos, agricultura' } },
    { id: 307, title: 'Refrigerado', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a refrigerated box truck (reefer) at a distribution center. He holds a temperature gauge and looks at the camera. The truck has an insulated box with a refrigeration unit on top. Bold white text overlay reads "VENDES UN REFRIGERADO?" with a purple CarMatch logo. Photorealistic, distribution center lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un refrigerado? Los de alimentos lo buscan', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Refrigerado, cadena de frio, alimentos, distribucion, logistica' } },
    { id: 308, title: 'Plataforma', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a flatbed truck (plataforma) loaded with a car. He looks at the camera with a thumbs up. The flatbed has a winch and tie-down points, with a vehicle secured on top. Bold white text overlay reads "VENDES UNA PLATAFORMA?" with a purple CarMatch logo. Photorealistic, auto transport yard lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una plataforma? Publicalo gratis', cta: 'Vende Gratis', segmentacion: { edad: '28-55', ubicacion: 'Mexico', intereses: 'Plataforma, transporte de autos, remolque, logistica' } },
    { id: 309, title: 'Caja Seca', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a dry van box truck (caja seca) at a loading dock. He holds a pallet jack and looks at the camera. The truck has a fully enclosed cargo box, roll-up rear door. Bold white text overlay reads "VENDES UNA CAJA SECA?" with a purple CarMatch logo. Photorealistic, warehouse loading dock lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una caja seca? Los transportistas te compran', cta: 'Vende Gratis', segmentacion: { edad: '28-55', ubicacion: 'Mexico', intereses: 'Caja seca, transporte de carga, logistica, distribucion' } },
    { id: 310, title: 'Grua', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a tow truck (grua) with a car being loaded. He holds a control pendant and looks at the camera. The tow truck has a boom, wheel lift, and flashing amber lights. Bold white text overlay reads "VENDES UNA GRUA?" with a purple CarMatch logo. Photorealistic, roadside lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una grua? Publicalo en CarMatch', cta: 'Vende Gratis', segmentacion: { edad: '28-55', ubicacion: 'Mexico', intereses: 'Grua, asistencia vial, transporte, emergencias' } },
    { id: 311, title: 'Hormigonera', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a concrete mixer truck (hormigonera) at a construction site. He holds a hard hat and looks at the camera. The truck has a large rotating drum, with concrete visible. Bold white text overlay reads "VENDES UNA HORMIGONERA?" with a purple CarMatch logo. Photorealistic, construction site lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una hormigonera? Los de construccion la buscan', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Hormigonera, concreto, construccion, obra, cemento' } },
    { id: 312, title: 'Portacoches / Madrina', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a car carrier truck (portacoches/madrina) loaded with multiple vehicles. He gestures toward the loaded truck and looks at the camera. The carrier has two levels of cars secured. Bold white text overlay reads "VENDES UN PORTACOCHES (MADRINA)?" with a purple CarMatch logo. Photorealistic, transport yard lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un portacoches (madrina)? Publicalo ya', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Portacoches, madrina, transporte de autos, logistica' } },
    { id: 313, title: 'Basurero', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a garbage truck (basurero) in a residential area. He holds a clipboard and looks at the camera. The truck has a compactor body, with mechanical arms for bins. Bold white text overlay reads "VENDES UN BASURERO?" with a purple CarMatch logo. Photorealistic, residential street lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un basurero? Municipalidades te buscan', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Basurero, recoleccion, residuos, municipio, limpieza' } },
    { id: 314, title: 'Chasis Cabina', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a chassis cab truck (chasis cabina) at a body builder shop. He gestures toward the bare chassis and looks at the camera. The truck has a frame ready for custom body installation. Bold white text overlay reads "VENDES UN CHASIS CABINA?" with a purple CarMatch logo. Photorealistic, body shop lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un chasis cabina? Publicalo gratis', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Chasis cabina, personalizacion, cuerpo, conversion, negocio' } },
    { id: 315, title: 'Bomberos', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a fire truck (bomberos) at a fire station. He holds a helmet and looks at the camera. The fire truck is red, with ladders, hoses, and emergency lights. Bold white text overlay reads "VENDES UN CAMION DE BOMBEROS?" with a purple CarMatch logo. Photorealistic, fire station lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un camion de bomberos? Publicalo en CarMatch', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Bomberos, emergencias, seguridad, protection civil' } },
    { id: 316, title: 'Blindado', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to an armored truck (blindado) at a secure facility. He gestures toward the reinforced vehicle and looks at the camera. The truck has thick armored panels, bulletproof glass, and security features. Bold white text overlay reads "VENDES UN CAMION BLINDADO?" with a purple CarMatch logo. Photorealistic, secure facility lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un camion blindado? Los de seguridad te buscan', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Blindado, seguridad, transporte de valores, proteccion' } },
    { id: 317, title: 'Compactador', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a garbage compactor truck (compactador) at a waste management facility. He holds a control panel and looks at the camera. The truck has a hydraulic compaction system. Bold white text overlay reads "VENDES UN COMPACTADOR?" with a purple CarMatch logo. Photorealistic, waste facility lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes un compactador? Municipalidades lo necesitan', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Compactador, residuos, municipio, limpieza urbana' } },
    { id: 318, title: 'Madre Nodriza', character: 'don-match', category: 'vehiculos', subcategory: 'Camion', prompt: 'Don Match, a 45-year-old Mexican man with a warm confident smile, wearing a dark blue CarMatch jacket, standing next to a tanker trailer (madre nodriza) at a fuel depot. He gestures toward the large tank and looks at the camera. The tanker is designed for transporting fuels or chemicals. Bold white text overlay reads "VENDES UNA MADRE NODRIZA?" with a purple CarMatch logo. Photorealistic, fuel depot lighting, professional Facebook ad style, 1080x1080.', hook: 'Vendes una madre nodriza? Publicalo ya', cta: 'Vende Gratis', segmentacion: { edad: '30-55', ubicacion: 'Mexico', intereses: 'Madre nodriza, transporte de combustible, logistica, petrolera' } },
]

export default function FacebookAdsTab() {
    const [searchTerm, setSearchTerm] = useState('')
    const [filterCharacter, setFilterCharacter] = useState<Character | 'all'>('all')
    const [filterCategory, setFilterCategory] = useState<Category | 'all'>('all')
    const [copiedId, setCopiedId] = useState<number | null>(null)
    const [expandedId, setExpandedId] = useState<number | null>(null)

    const filteredPrompts = useMemo(() => {
        return allPrompts.filter(prompt => {
            const matchesSearch = prompt.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                prompt.hook.toLowerCase().includes(searchTerm.toLowerCase())
            const matchesCharacter = filterCharacter === 'all' || prompt.character === filterCharacter
            const matchesCategory = filterCategory === 'all' || prompt.category === filterCategory
            return matchesSearch && matchesCharacter && matchesCategory
        })
    }, [searchTerm, filterCharacter, filterCategory])

    const copyToClipboard = async (text: string, id: number) => {
        await navigator.clipboard.writeText(text)
        setCopiedId(id)
        setTimeout(() => setCopiedId(null), 2000)
    }

    const stats = useMemo(() => {
        const byCharacter = allPrompts.reduce((acc, p) => {
            acc[p.character] = (acc[p.character] || 0) + 1
            return acc
        }, {} as Record<string, number>)
        return byCharacter
    }, [])

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex items-center gap-3">
                <Facebook className="w-8 h-8 text-blue-500" />
                <h3 className="text-2xl font-black italic tracking-tighter uppercase">Facebook Ads Prompts</h3>
                <span className="ml-auto text-sm text-zinc-500">{allPrompts.length} prompts</span>
            </div>

            {/* Character Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {Object.entries(characters).map(([key, char]) => (
                    <div key={key} className="bg-[#111114] rounded-xl border border-white/5 p-4 text-center">
                        <char.icon className={`w-6 h-6 mx-auto mb-2 ${char.color}`} />
                        <div className="text-white font-bold text-sm">{char.name}</div>
                        <div className="text-zinc-500 text-xs">{stats[key] || 0} prompts</div>
                    </div>
                ))}
            </div>

            {/* Filters */}
            <div className="flex flex-col md:flex-row gap-3">
                <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-500" />
                    <input
                        type="text"
                        placeholder="Buscar prompts..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 bg-[#111114] border border-white/10 rounded-xl text-white placeholder-zinc-500 focus:outline-none focus:border-primary-500"
                    />
                </div>
                <select
                    value={filterCharacter}
                    onChange={(e) => setFilterCharacter(e.target.value as Character | 'all')}
                    className="px-4 py-3 bg-[#111114] border border-white/10 rounded-xl text-white focus:outline-none focus:border-primary-500"
                >
                    <option value="all">Todos los personajes</option>
                    {Object.entries(characters).map(([key, char]) => (
                        <option key={key} value={key}>{char.name}</option>
                    ))}
                </select>
                <select
                    value={filterCategory}
                    onChange={(e) => setFilterCategory(e.target.value as Category | 'all')}
                    className="px-4 py-3 bg-[#111114] border border-white/10 rounded-xl text-white focus:outline-none focus:border-primary-500"
                >
                    <option value="all">Todas las categorias</option>
                    <option value="negocios">Negocios (39)</option>
                    <option value="vehiculos">Vehiculos (97)</option>
                </select>
            </div>

            {/* Results count */}
            <div className="text-zinc-500 text-sm">
                Mostrando {filteredPrompts.length} de {allPrompts.length} prompts
            </div>

            {/* Prompts Grid */}
            <div className="grid gap-4">
                {filteredPrompts.map((prompt) => {
                    const char = characters[prompt.character]
                    const isExpanded = expandedId === prompt.id

                    return (
                        <div
                            key={prompt.id}
                            className="bg-[#111114] rounded-xl border border-white/5 overflow-hidden hover:border-white/10 transition-colors"
                        >
                            {/* Header */}
                            <div
                                className="flex items-center gap-3 p-4 cursor-pointer"
                                onClick={() => setExpandedId(isExpanded ? null : prompt.id)}
                            >
                                <char.icon className={`w-5 h-5 ${char.color}`} />
                                <div className="flex-1">
                                    <div className="text-white font-bold text-sm">{prompt.title}</div>
                                    <div className="text-zinc-500 text-xs">{char.name} · {prompt.category} · {prompt.subcategory}</div>
                                </div>
                                <div className="flex gap-2">
                                    <button
                                        onClick={(e) => { e.stopPropagation(); copyToClipboard(prompt.prompt, prompt.id * 10 + 1) }}
                                        className="px-3 py-1.5 bg-primary-500/10 text-primary-400 rounded-lg text-xs font-bold hover:bg-primary-500/20 transition-colors"
                                    >
                                        {copiedId === prompt.id * 10 + 1 ? 'Copiado!' : 'Prompt'}
                                    </button>
                                    <button
                                        onClick={(e) => { e.stopPropagation(); copyToClipboard(prompt.hook, prompt.id * 10 + 2) }}
                                        className="px-3 py-1.5 bg-orange-500/10 text-orange-400 rounded-lg text-xs font-bold hover:bg-orange-500/20 transition-colors"
                                    >
                                        {copiedId === prompt.id * 10 + 2 ? 'Copiado!' : 'Hook'}
                                    </button>
                                </div>
                            </div>

                            {/* Expanded Content */}
                            {isExpanded && (
                                <div className="px-4 pb-4 space-y-3 border-t border-white/5 pt-3">
                                    {/* Prompt */}
                                    <div>
                                        <div className="text-zinc-400 text-xs font-bold mb-1">PROMPT (Gemini):</div>
                                        <div className="bg-black/50 rounded-lg p-3 text-zinc-300 text-sm font-mono whitespace-pre-wrap">
                                            {prompt.prompt}
                                        </div>
                                    </div>

                                    {/* Hook */}
                                    <div>
                                        <div className="text-zinc-400 text-xs font-bold mb-1">HOOK (Facebook):</div>
                                        <div className="bg-black/50 rounded-lg p-3 text-white text-sm font-bold">
                                            {prompt.hook}
                                        </div>
                                    </div>

                                    {/* CTA & Segmentacion */}
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                        <div>
                                            <div className="text-zinc-400 text-xs font-bold mb-1">CTA:</div>
                                            <div className="bg-primary-500/10 text-primary-400 rounded-lg p-2 text-sm font-bold text-center">
                                                {prompt.cta}
                                            </div>
                                        </div>
                                        <div>
                                            <div className="text-zinc-400 text-xs font-bold mb-1">SEGMENTACION:</div>
                                            <div className="bg-black/50 rounded-lg p-3 text-zinc-300 text-xs space-y-1">
                                                <div>Edad: {prompt.segmentacion.edad}</div>
                                                <div>Ubicacion: {prompt.segmentacion.ubicacion}</div>
                                                <div>Intereses: {prompt.segmentacion.intereses}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    )
                })}
            </div>
        </div>
    )
}
